name: 'whyline_denver_dbt'
version: '1.0'
profile: 'whyline_denver'
model-paths: ['models']
target-path: 'target'
clean-targets: ['target']
models:
  whyline_denver_dbt:
    +materialized: view
    staging:
      +schema: "{{ env_var('BQ_DATASET_STG', 'stg_denver') }}"
    intermediate:
      +schema: "{{ env_var('BQ_DATASET_STG', 'stg_denver') }}"
    marts:
      +schema: "{{ env_var('BQ_DATASET_MART', 'mart_denver') }}"
      +tags: ["marts"]
vars:
  on_time_sec: 300
  headway_tol_ratio: 0.5
  sched_match_tol_sec: 1800
  weather_station: "USW00023062"
  weather_lookback_days: 30
