name: whylinedenver
version: 0.1.0
config-version: 2

profile: whylinedenver

model-paths:
  - models
macro-paths:
  - macros

analysis-paths: []
test-paths: []
data-paths: []
seed-paths: []
snapshot-paths: []

clean-targets:
  - target
  - dbt_packages

models:
  whylinedenver:
    staging:
      +materialized: view
    marts:
      +materialized: table
      reliability:
        +schema: reliability
      safety:
        +schema: safety
      access:
        +schema: access
      equity:
        +schema: equity
