name: 'whylinedenver_dbt'
version: '1.0'
profile: 'whylinedenver'
model-paths: ['models']
target-path: 'target'
clean-targets: ['target']
models:
  whylinedenver_dbt:
    +materialized: view
    staging:
      +schema: "{{ env_var('BQ_DATASET_STG', 'stg_denver') }}"
