whylinedenver:
  target: ${DBT_TARGET}
  outputs:
    duckdb:
      type: duckdb
      threads: {{ env_var('DUCKDB_THREADS', 4) }}
      path: {{ env_var('WHYLN_DUCKDB_PATH', 'data/warehouse.duckdb') }}
      schema: analytics
    bigquery:
      type: bigquery
      method: service-account
      project: {{ env_var('BIGQUERY_PROJECT') }}
      dataset: {{ env_var('BIGQUERY_DATASET', 'analytics') }}
      location: {{ env_var('BIGQUERY_LOCATION', 'US') }}
      threads: 4
      priority: interactive
      keyfile: {{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}
      retries: 2
