whylinedenver:
  outputs:
    demo:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'data/warehouse.duckdb') }}"
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_MART') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      priority: interactive
  target: "{{ env_var('DBT_TARGET', 'demo') }}"
