whyline_denver:
  outputs:
    prod:
      type: bigquery
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_MART') }}"
      location: US
      priority: interactive
      method: "{{ 'service-account' if env_var('GOOGLE_APPLICATION_CREDENTIALS', '') else 'oauth' }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '') }}"
  target: "{{ env_var('DBT_TARGET', 'prod') }}"
