name: CI

on:
  pull_request: {}
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      - name: Lint
        run: make lint

      - name: Tests
        run: make test

      - name: Ingestion smoke tests
        run: make test-ingest

  docs:
    # Only deploy docs on pushes to main (not PRs)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure GCP credentials
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT" > ${{ github.workspace }}/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV

      - name: Set environment variables
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/dbt/profiles
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          BQ_DATASET_RAW: ${{ secrets.BQ_DATASET_RAW }}
          BQ_DATASET_STG: ${{ secrets.BQ_DATASET_STG }}
          BQ_DATASET_MART: ${{ secrets.BQ_DATASET_MART }}
        run: |
          echo "DBT_PROFILES_DIR=$DBT_PROFILES_DIR" >> $GITHUB_ENV
          echo "GCP_PROJECT_ID=$GCP_PROJECT_ID" >> $GITHUB_ENV
          echo "BQ_DATASET_RAW=$BQ_DATASET_RAW" >> $GITHUB_ENV
          echo "BQ_DATASET_STG=$BQ_DATASET_STG" >> $GITHUB_ENV
          echo "BQ_DATASET_MART=$BQ_DATASET_MART" >> $GITHUB_ENV

      - name: Build dbt docs
        run: make pages-build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

  deploy:
    # Only deploy on pushes to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
