name: Nightly Ingest

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure gcloud credentials
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT" > ${{ github.workspace }}/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV

      - name: Ingest datasets and load to BigQuery
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          BQ_DATASET_RAW: ${{ secrets.BQ_DATASET_RAW }}
          NOAA_CDO_TOKEN: ${{ secrets.NOAA_CDO_TOKEN }}
        run: make nightly-ingest-bq
