name: Realtime GTFS-RT Snapshots

on:
  schedule:
    # Micro-batch every 5 minutes (24/7) to approximate realtime snapshots
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure gcloud credentials
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT" > ${{ github.workspace }}/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV

      - name: Capture GTFS-RT snapshots
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        run: |
          PYTHONPATH=$PWD/src python -m whylinedenver.ingest.gtfs_realtime \
            --gcs --bucket $GCS_BUCKET \
            --snapshots 1
