[server]
baseUrlPath = "/app"
headless = true
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true
cookieSameSite = "none"
cookieSecure = true

[browser]
gatherUsageStats = false
serverAddress = ""
serverPort = 443
